const takeNotesTypes = {
  SET_NOTE_TITLE: `SET_NOTE_TITLE`,
  SET_NOTES_DETAILS: `SET_NOTES_DETAILS`,
  SET_GOTTEN_TITLE: `SET_GOTTEN_TITLE`,
  SET_GOTTEN_DATE: `SET_GOTTEN_DATE`,
  SET_GOTTEN_DETAILS: `SET_GOTTEN_DETAILS`,
  SET_IS_RELOADING_PAGE: `SET_IS_RELOADING_PAGE`,
  SET_IS_SIDEBAR_NOTE_CLICKED: `SET_IS_SIDEBAR_NOTE_CLICKED`,
  SET_IS_UPDATING_NOTE: `SET_IS_UPDATING_NOTE`,
};

export default takeNotesTypes;
