const appTypes = {
  SET_NOTE_CONTENT: `SET_NOTE_CONTENT`,
  SET_NOTES_PAGE_GOTTEN_TITLE: `SET_NOTES_PAGE_GOTTEN_TITLE`,
  SET_NOTES_PAGE_GOTTEN_DATE: `SET_NOTES_PAGE_GOTTEN_DATE`,
  SET_NOTES_PAGE_GOTTEN_DETAILS: `SET_NOTES_PAGE_GOTTEN_DETAILS`,
  SET_NOTE_KEY: `SET_NOTES_KEY`,
  SET_IS_NOTES_PAGE_NOTE_CLICKED: `SET_IS_NOTES_PAGE_NOTE_CLICKED`,
  SET_IS_DELETE_BTN_CLICKED: `SET_IS_DELETE_BTN_CLICKED`,

  // DELETE_NOTE_START: `DELETE_NOTE_START`,
  // DELETE_NOTE_SUCCESS: `DELETE_NOTE_SUCCESS`,
  // DELETE_NOTE_FAILURE: `DELETE_NOTE_FAILURE`,
  // SELECT_NOTE_START: `SELECT_NOTE_START`,
  // SELECT_NOTE_SUCCESS: `SELECT_NOTE_SUCCESS`,
  // SELECT_NOTE_FAIURE: `SELECT_NOTE_FAIURE`,
};

export default appTypes;
